"""RL training monitor with convergence detection and plateau alerts.

Tracks training metrics over time and detects:
- Convergence (reward stabilizes near target)
- Plateau (reward stops improving for N epochs)
- Divergence (reward drops significantly)
- NaN/Inf anomalies
"""

from __future__ import annotations

import enum
import time
from collections import deque
from dataclasses import dataclass, field
from typing import Any


class TrainingPhase(enum.Enum):
    WARMUP = "warmup"
    IMPROVING = "improving"
    PLATEAU = "plateau"
    CONVERGED = "converged"
    DIVERGING = "diverging"
    UNKNOWN = "unknown"


@dataclass(slots=True)
class MetricSnapshot:
    """A single metric observation."""

    epoch: int
    value: float
    timestamp: float
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(slots=True)
class TrainingAlert:
    """An alert generated by the monitor."""

    alert_type: str
    message: str
    epoch: int
    severity: str = "info"  # info, warning, critical
    details: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "alert_type": self.alert_type,
            "message": self.message,
            "epoch": self.epoch,
            "severity": self.severity,
            "details": self.details,
        }


class TrainingMonitor:
    """Monitor RL training metrics for convergence and anomalies.

    Parameters
    ----------
    window_size:
        Number of recent epochs to consider for plateau/convergence detection.
    plateau_threshold:
        Maximum relative improvement considered a plateau.
    convergence_threshold:
        Maximum variance (relative to mean) to consider converged.
    divergence_drop:
        Fractional drop from recent peak to trigger divergence alert.
    warmup_epochs:
        Number of epochs before analysis begins.
    """

    def __init__(
        self,
        window_size: int = 20,
        plateau_threshold: float = 0.01,
        convergence_threshold: float = 0.02,
        divergence_drop: float = 0.2,
        warmup_epochs: int = 10,
    ) -> None:
        self._window_size = max(3, window_size)
        self._plateau_threshold = plateau_threshold
        self._convergence_threshold = convergence_threshold
        self._divergence_drop = divergence_drop
        self._warmup_epochs = warmup_epochs

        self._metrics: dict[str, deque[MetricSnapshot]] = {}
        self._alerts: list[TrainingAlert] = []
        self._phase = TrainingPhase.UNKNOWN
        self._peak_reward: float = float("-inf")
        self._run_id: str = ""

    def start_monitoring(self, run_id: str) -> None:
        """Begin monitoring a new training run."""
        self._run_id = run_id
        self._metrics.clear()
        self._alerts.clear()
        self._phase = TrainingPhase.WARMUP
        self._peak_reward = float("-inf")

    def record_metric(self, name: str, epoch: int, value: float, metadata: dict[str, Any] | None = None) -> list[TrainingAlert]:
        """Record a metric observation and return any new alerts."""
        if name not in self._metrics:
            self._metrics[name] = deque(maxlen=self._window_size * 3)

        snapshot = MetricSnapshot(
            epoch=epoch,
            value=value,
            timestamp=time.monotonic(),
            metadata=metadata or {},
        )
        self._metrics[name].append(snapshot)

        new_alerts: list[TrainingAlert] = []

        # Check for NaN/Inf
        if value != value or abs(value) == float("inf"):
            alert = TrainingAlert(
                alert_type="anomaly",
                message=f"NaN/Inf detected in {name} at epoch {epoch}",
                epoch=epoch,
                severity="critical",
                details={"metric": name, "value": str(value)},
            )
            new_alerts.append(alert)

        # Only analyze reward metric for phase detection
        if name == "reward":
            new_alerts.extend(self._analyze_reward(epoch))

        self._alerts.extend(new_alerts)
        return new_alerts

    def _analyze_reward(self, epoch: int) -> list[TrainingAlert]:
        """Analyze reward metric for phase transitions."""
        alerts: list[TrainingAlert] = []
        snapshots = self._metrics.get("reward")
        if snapshots is None or len(snapshots) < 3:
            return alerts

        values = [s.value for s in snapshots]
        latest = values[-1]

        # Track peak
        if latest > self._peak_reward:
            self._peak_reward = latest

        # Warmup phase
        if epoch < self._warmup_epochs:
            self._phase = TrainingPhase.WARMUP
            return alerts

        # Get recent window
        window = values[-self._window_size:] if len(values) >= self._window_size else values
        if len(window) < 3:
            return alerts

        mean = sum(window) / len(window)
        variance = sum((v - mean) ** 2 for v in window) / len(window)
        std = variance ** 0.5
        rel_std = std / abs(mean) if abs(mean) > 1e-8 else std

        # Check convergence (low variance over window)
        if rel_std < self._convergence_threshold and self._phase != TrainingPhase.CONVERGED:
            self._phase = TrainingPhase.CONVERGED
            alerts.append(TrainingAlert(
                alert_type="convergence",
                message=f"Training converged at epoch {epoch} (rel_std={rel_std:.4f})",
                epoch=epoch,
                severity="info",
                details={"mean_reward": round(mean, 4), "rel_std": round(rel_std, 4)},
            ))
            return alerts

        # Check plateau (recent improvement below threshold)
        first_half = window[: len(window) // 2]
        second_half = window[len(window) // 2:]
        mean_first = sum(first_half) / len(first_half)
        mean_second = sum(second_half) / len(second_half)
        improvement = (mean_second - mean_first) / (abs(mean_first) + 1e-8)

        if abs(improvement) < self._plateau_threshold and self._phase != TrainingPhase.PLATEAU:
            self._phase = TrainingPhase.PLATEAU
            alerts.append(TrainingAlert(
                alert_type="plateau",
                message=f"Training plateau detected at epoch {epoch}",
                epoch=epoch,
                severity="warning",
                details={"improvement": round(improvement, 6), "mean_reward": round(mean, 4)},
            ))
            return alerts

        # Check divergence (significant drop from peak)
        if self._peak_reward > 0:
            drop = (self._peak_reward - latest) / self._peak_reward
        elif self._peak_reward < 0:
            drop = (latest - self._peak_reward) / abs(self._peak_reward)
        else:
            drop = 0.0

        if drop > self._divergence_drop and self._phase != TrainingPhase.DIVERGING:
            self._phase = TrainingPhase.DIVERGING
            alerts.append(TrainingAlert(
                alert_type="divergence",
                message=f"Training diverging at epoch {epoch} (drop={drop:.2%})",
                epoch=epoch,
                severity="critical",
                details={"peak": round(self._peak_reward, 4), "current": round(latest, 4), "drop": round(drop, 4)},
            ))
            return alerts

        # Default: improving
        if improvement > self._plateau_threshold:
            self._phase = TrainingPhase.IMPROVING

        return alerts

    @property
    def phase(self) -> TrainingPhase:
        return self._phase

    @property
    def alerts(self) -> list[TrainingAlert]:
        return list(self._alerts)

    def get_metric_history(self, name: str, last_n: int = 0) -> list[dict[str, Any]]:
        """Return metric history."""
        snapshots = self._metrics.get(name, deque())
        items = list(snapshots)
        if last_n > 0:
            items = items[-last_n:]
        return [{"epoch": s.epoch, "value": s.value} for s in items]

    def get_summary(self) -> dict[str, Any]:
        """Full monitoring summary."""
        metric_summaries: dict[str, Any] = {}
        for name, snapshots in self._metrics.items():
            values = [s.value for s in snapshots]
            if values:
                metric_summaries[name] = {
                    "count": len(values),
                    "latest": round(values[-1], 4),
                    "min": round(min(values), 4),
                    "max": round(max(values), 4),
                    "mean": round(sum(values) / len(values), 4),
                }

        return {
            "run_id": self._run_id,
            "phase": self._phase.value,
            "metrics": metric_summaries,
            "total_alerts": len(self._alerts),
            "recent_alerts": [a.to_dict() for a in self._alerts[-5:]],
        }
