"""Known Isaac Sim log error/warning patterns and remediation guidance."""

from __future__ import annotations

ERROR_PATTERNS: list[dict[str, str]] = [
    {
        "category": "usd_stage",
        "pattern": r"USD Stage Error.*Cannot find prim at path '([^']+)'",
        "severity": "error",
        "description": "USD prim not found at expected path",
        "fix": "Check that the USD scene is loaded and that the prim path is correct.",
    },
    {
        "category": "usd_stage",
        "pattern": r"Failed to open layer.*\.usd",
        "severity": "error",
        "description": "USD file failed to load",
        "fix": "Verify the file exists, permissions are valid, and USD versions are compatible.",
    },
    {
        "category": "usd_stage",
        "pattern": r"Warning:.*attribute.*has no authored value",
        "severity": "warning",
        "description": "USD attribute missing authored value",
        "fix": "Non-critical. The attribute will use fallback defaults.",
    },
    {
        "category": "usd_stage",
        "pattern": r"Cannot resolve reference.*\.usd",
        "severity": "error",
        "description": "USD reference cannot be resolved",
        "fix": "Check missing assets and relative/absolute USD reference paths.",
    },
    {
        "category": "physics",
        "pattern": r"PhysX.*[Ee]rror.*",
        "severity": "error",
        "description": "PhysX engine error",
        "fix": "Validate physics scene setup, collision meshes, and object masses.",
    },
    {
        "category": "physics",
        "pattern": r"Physics step.*NaN|inf",
        "severity": "critical",
        "description": "Physics instability produced NaN/Inf",
        "fix": "Reset simulation and inspect object masses/colliders/initial overlaps.",
    },
    {
        "category": "physics",
        "pattern": r"Articulation.*invalid joint",
        "severity": "error",
        "description": "Invalid articulation joint configuration",
        "fix": "Validate URDF/USD joint type, limits, and hierarchy definitions.",
    },
    {
        "category": "physics",
        "pattern": r"collision.*overlap.*detected",
        "severity": "warning",
        "description": "Collision overlap detected",
        "fix": "Move intersecting bodies or fix collision layer/filtering setup.",
    },
    {
        "category": "rendering",
        "pattern": r"RTX.*[Ee]rror|Hydra.*[Ee]rror",
        "severity": "error",
        "description": "RTX/Hydra rendering pipeline error",
        "fix": "Check driver compatibility and GPU availability.",
    },
    {
        "category": "rendering",
        "pattern": r"Out of.*memory|GPU memory|CUDA.*out.*memory",
        "severity": "critical",
        "description": "GPU out-of-memory condition",
        "fix": "Reduce render load, texture/sensor count, or scene complexity.",
    },
    {
        "category": "rendering",
        "pattern": r"Vulkan.*[Ee]rror|VkResult",
        "severity": "error",
        "description": "Vulkan API error",
        "fix": "Update drivers and verify Vulkan runtime compatibility.",
    },
    {
        "category": "rendering",
        "pattern": r"[Ss]hader.*compilation.*fail",
        "severity": "error",
        "description": "Shader compilation failure",
        "fix": "Validate shader/material definitions and MDL resource paths.",
    },
    {
        "category": "extension",
        "pattern": r"Extension.*failed to load|Cannot load extension",
        "severity": "error",
        "description": "Isaac extension failed to load",
        "fix": "Check extension compatibility and dependencies in Isaac Sim extensions panel.",
    },
    {
        "category": "extension",
        "pattern": r"omni\.isaac\.ros2_bridge.*[Ee]rror",
        "severity": "error",
        "description": "ROS2 bridge extension error",
        "fix": "Confirm ROS bridge enabled and domain/QoS configuration is aligned.",
    },
    {
        "category": "python",
        "pattern": r"Traceback \(most recent call last\)",
        "severity": "error",
        "description": "Python traceback detected",
        "fix": "Read following traceback lines to identify the root cause.",
    },
    {
        "category": "python",
        "pattern": r"ModuleNotFoundError: No module named '([^']+)'",
        "severity": "error",
        "description": "Missing Python module",
        "fix": "Install missing module in the Python environment used by Isaac Sim.",
    },
    {
        "category": "python",
        "pattern": r"ImportError.*omni\.isaac",
        "severity": "error",
        "description": "Isaac module import failed",
        "fix": "Run script inside Isaac Sim runtime or bundled Python environment.",
    },
    {
        "category": "ros2_bridge",
        "pattern": r"DDS.*discovery.*failed|FastDDS.*error",
        "severity": "error",
        "description": "ROS2 DDS discovery failure",
        "fix": "Validate DDS profiles, networking mode, and ROS domain alignment.",
    },
    {
        "category": "ros2_bridge",
        "pattern": r"topic.*not.*publish|subscriber.*timeout",
        "severity": "warning",
        "description": "ROS2 topic not publishing or subscriber timeout",
        "fix": "Verify topic existence, QoS compatibility, and bridge availability.",
    },
    {
        "category": "performance",
        "pattern": r"Frame.*time.*exceeded|render.*fps.*below",
        "severity": "warning",
        "description": "Render performance degradation",
        "fix": "Reduce quality settings, camera count, or scene complexity.",
    },
    {
        "category": "performance",
        "pattern": r"Physics.*step.*too slow|simulation.*behind.*real.*time",
        "severity": "warning",
        "description": "Simulation lag behind real-time",
        "fix": "Tune physics step, simplify colliders, or reduce articulated load.",
    },
]
